apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}-ingress
  namespace: default
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{.Values.ingressHost}}
    http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: {{.Release.Name}}-svc
            port:
              number: {{.Values.servicePort}}